diploiTemplateVersion: V1.0
name: diploi-astro
description: Astro is an all-in-one web framework for building fast, content-focused websites.
defaultName: Astro

stages:
  - name: Development
    identifier: development
  - name: Staging
    identifier: staging
  - name: Production
    identifier: production

contexts:
  - name: app
    identifier: app

parameterGroups:
  - name: PostgreSQL Database
    identifier: postgres
    toggleable: true
    description: Database connection info
    defaultValue: FALSE
    parameters:
      - name: Host
        identifier: POSTGRES_HOST
        defaultValue: postgres
        type: string
      - name: Port
        identifier: POSTGRES_PORT
        defaultValue: 5432
        type: integer
      - name: User
        identifier: POSTGRES_USER
        defaultValue: postgres
        type: string
        contexts: label=postgres,label=app
      - name: Password
        identifier: POSTGRES_PASSWORD
        defaultValue: postgres
        type: secret
      - name: Schema
        identifier: POSTGRES_DB
        defaultValue: astro
        type: string

repositories:
  - name: app
    identifier: app

hosts:
  - name: App
    identifier: app
    urlFormat: '[name].[default-domain]'

ssh:
  - usernameFormat: 'app'
    contexts: label=app
    stages:
      - development
      - staging
  - usernameFormat: 'app-[index]'
    contexts: label=app
    stages:
      - production

logs:
  - identifier: www-log
    name: Astro Log
    labelSelector: app=app
    command: tail -n 2000 -F /var/log/www.log

images:
  - identifier: app
    repository: app
    dockerfile: Dockerfile
    image: ghcr.io/diploi/astro-template
    initialProjectImage: ghcr.io/diploi/astro-template-initial-project
    stages:
      - development
      - production
      - staging
    manualBuildStages:
      - development

storage:
  - identifier: app
    stages:
      - development
    sizeMiB: 6144
  - identifier: postgres
    stages:
      - production
      - staging
      - development
    sizeMiB: 4096

status:
  url: http://app:3000/status
